name: main.deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-init:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: INICIANDO A PUBLICAÇÃO
        run: echo INICIANDO...

      - name: npm install, build, and test
        run: |
            npm install
            npm run build --if-present
            npm install pm2@latest -g

  producao-deploy:
    env:
      USUARIO: aluno22-ppiadsead
      SENHA: aluno22-ppiadsead
    if: github.ref == 'refs/heads/main'
    needs: [deploy-init]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: INICIANDO A PUBLICAÇÃO PARA PRODUÇÃO
        run: echo INICIANDO... 
        
      - name: Conectar via SSH no servidor de Produção e realizar a publicação.
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 129.146.32.171
          username: ${{ env.USUARIO }}
          password: ${{ env.SENHA }}
          port: 22
          source: "*"
          target: "/home/${{ env.USUARIO }}/htdocs/${{ env.USUARIO }}.fake.edu.br/"

      - name: Reiniciando a aplicação
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 129.146.32.171
          username: ${{ env.USUARIO }}
          password: ${{ env.SENHA }}
          port: 22
          script: |
            node /home/${{ env.USUARIO }}/htdocs/${{ env.USUARIO }}.fake.edu.br/index.js
